apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kubesecure-servicemonitor
  namespace: monitoring

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}

  endpoints:
    - port: http
      path: /metrics
      interval: 15s